language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc

script:
  - rm -rf build
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release -DENABLE_G3LOG=OFF ..
  - make VERBOSE=1 -j 8
